apiVersion: v1
kind: Service
metadata:
  name: 20211104-nginx
spec:
  selector:
    app: 20211104-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30010
  type: NodePort
