apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-nginx
  labels:
    app: ng-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ng-nginx
  template:
    metadata:
      labels:
        app: ng-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
