apiVersion: apps/v1
kind: Deployment
metadata:
  name: 20211104-nginx
  labels:
    app: 20211104-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 20211104-nginx
  template:
    metadata:
      labels:
        app: 20211104-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
