apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-nginx
  labels:
    app: ng-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ng-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: ng-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.0
      imagePullSecrets:
        - name: harborsecret
