apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ng-nginx
  labels:
    app: ng-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ng-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ng-nginx
    spec:
      containers:
        - name: nginx
          image: 10.1.1.251:443/admin/nginx
      imagePullSecrets:
        - name: regcred
