apiVersion: v1
kind: Service
metadata:
  labels:
    app: ng-nginx
  name: ng-nginx
spec:
  selector:
    app: ng-nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  externalIPs:
    - 10.1.1.21
