apiVersion: v1
kind: Service
metadata:
  labels:
    app: ng-nginx
  name: ng-nginx
spec:
  selector:
    app: ng-nginx
  ports:
    - port: 880
      protocol: TCP
      targetPort: 80
      nodePort: 30010
  type: NodePort
