apiVersion: v1
kind: Service
metadata:
  labels:
    app: ng-nginx
    color: blue
  name: ng-nginx
spec:
  selector:
    app: ng-nginx
    color: blue
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30010
  type: NodePort
